[package]
name = "amelius"
version = "0.1.0"
authors = ["Raoul Duke <teddymorales@utexas.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
